name: dansertodiscord
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.8
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  path: ^1.9.1
  intl: ^0.20.2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
